# Generated by Django 5.2.3 on 2025-06-29 21:41

import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enfermaria', models.CharField(choices=[('SUR', 'Serviço de Urgência e Reanimação'), ('PED', 'Pediatria'), ('CIR', 'Cirurgia'), ('GIN', 'Ginecologia'), ('OBST', 'Obstetrícia'), ('UROL', 'Urologia'), ('MED_I', 'Medicina - Homens'), ('MED_II', 'Medicina - Mulheres'), ('OFT', 'Oftalmologia'), ('C.EXT', 'Consulta Externa')], max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSanguineo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo Sanguíneo',
                'verbose_name_plural': 'Tipos Sanguíneos',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('nascimento', models.DateField()),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], max_length=10)),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(max_length=13, region='MZ')),
                ('residencia', models.CharField(blank=True, max_length=100, null=True)),
                ('nacionalidade', django_countries.fields.CountryField(default='MZ', max_length=2)),
                ('identificacao', models.CharField(blank=True, max_length=20, null=True)),
                ('entrada', models.DateTimeField(auto_now_add=True)),
                ('enfermaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.enfermaria')),
                ('tipo_sanguineo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.tiposanguineo')),
            ],
            options={
                'verbose_name_plural': 'Pacientes',
            },
        ),
    ]
